server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=100
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=1209600000

# CORS Configuration
cors.allowed-origins=http://localhost:3000,http://localhost:3001,http://localhost:3002
cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
cors.max-age=3600
